### PR TITLE
pixi 5.0.0-rc compatibility

### PR DESCRIPTION
**Pull request by amir-arad**

### CODE REVIEW

**Review by yordan-kanchelov — APPROVED** [review]
Neat, thanks for the patch. I will update it shortly to npm soon

**Review by yordan-kanchelov — COMMENTED** [review]
package.json needs to be updated with the new pixi v5 deps

**Comment by amir-arad** [comment]
> package.json needs to be updated with the new pixi v5 deps

there is only `@types/pixi.js` dep. and it doesn't have a 5 version yet... 
I use `pixi.js` dependency for typings myself, so I did that.

legit?

**Review by yordan-kanchelov — APPROVED** [review]
With this everything seems great now. I will merge it as soon as possible tonight.  Only need to create a branch and leave it with v4 compatibility.

**Pull request merged**
